ornladios/ADIOS

- utils/bpmeta/CMakeLists.txt
- utils/bpmeta/Makefile.am
@pnorbert `bpmeta` is a threaded tool and failed the `make` build target in its linker step on most Linux systems I used it so far (Debian, Ubunty, Rhea, ...).
This added dependency fixes it.
> bpmeta: Fix missing `-pthread` linker dependency

- Makefile.am
Renaming of the README did have a side effect on
./autogen.sh since autotools expect an actual README file.
This fixes https://github.com/ornladios/ADIOS/pull/76, similar as proposed in
http://stackoverflow.com/questions/15013672/use-autotools-with-readme-md
@pnorbert sorry, that's a bit awkward :D CI will protect us in the future from my stupidity
> Fix automake (README)

- utils/gpp/ad_config.py
- utils/gpp/gpp.py.in
Fixes show-stoppers in python scripts that prevent install on python3 only systems.
Fixes mainly `print()` calls.
This change is fully python2 compatible.
https://stackoverflow.com/questions/13415181/brackets-around-print-in-python/13415304#13415304
First seen with automates testing in
https://travis-ci.org/ComputationalRadiationPhysics/pyDive/jobs/101651336
> Python3: gcc fixes / linter / config

- autogen.sh
add the missing shebang in a portable way to `autogen.sh`
> autogen.sh: add shebang

- tests/suite/programs/adios_amr_write.c
- tests/suite/programs/adios_amr_write_2vars.c
add missing include to fix the warning `incompatible implicit declaration of built-in function ‘exit’`
> fix warning `implicit declaration ... function "exit"`

- src/core/common_adios.c
I missed one "return" statement for issuing an exit event for adios_group_size().
> Missing timer stop for adios_group_size()

- src/core/flexpath.h
- src/write/adios_flexpath.c
I added the queue_size parameter functionality back into flexpath2.0 after we lost it in the flexpath1.0 upgrade.  It passes all of the flexpath regression tests and a few additional ones that I've run to make sure the code works as intended.
> Queue_size parameter for Flexpath

- CMakeLists.txt
- config.h.cmake
- tests/C/flexpath_tests/global_range_select/CMakeLists.txt.orig
- utils/bpls/CMakeLists.txt
- utils/bpls/bpls.h
- utils/skeldump/skeldump.h
- config.h.cmake: add `HAVE_STRNDUP`
- CMake: add check for `HAVE_STRNDUP`
- add missing include "config.h"
- bpls: add missing include directory
warning:
```C++
adios/utils/skeldump/skeldump.h:23:0: warning: "strndup" redefined
```
> fix warning `redefine strndup`

- src/core/a2sel.c
- src/core/adios.c
- src/core/adios_internals.c
- src/core/adios_internals_mxml.c
- src/core/adiost_callback_internal.c
- src/core/adiost_callback_internal.h
- src/core/adiost_default_tool.c
- src/core/common_adios.c
- src/core/common_read.c
- src/public/adiost_callback_api.h
- src/read/read_bp.c
- src/read/read_flexpath.c
- src/write/adios_flexpath.c
- src/write/adios_mpi_amr.c
I went through the ADIOS 1.12 documentation and added ADIOST callbacks for all relevant (not deprecated) adios_* API calls discussed in the documentation.
> Complete the callback support for full API

- src/core/common_read.c
For the ADIOST callback functions, some pointers required a
cast to const so the tool can't modify the contents.
> Adding "const" casts for pointer arguments

- src/transforms/adios_transform_blosc_read.c
- src/transforms/adios_transform_bzip2_read.c
- src/transforms/adios_transform_lz4_read.c
- src/transforms/adios_transform_zlib_read.c
fix #161
Avoid null pointer dereferencing during the read of transformed data of size zero
- bzip2
- lz4
- blosc
- zlib
Zero-sized data occurs regularly on read of parallel files that store unstructured data such as particles. In domain decomposition over MPI ranks, some ranks do not hold particles at a certain point in time and due to that write zero particles (into a N>0 sized global variable).
> fix read of zero size transformed data

- src/core/transforms/adios_transforms_read.c
`adios_schedule_read` is reading the whole variable if the selection is `NULL`. This creates an invalid memory access if the variable is using adios transforms.
Reading a transformed variable with the following commands produce the issue
```
size_t start = 0;
size_t end = vi->dims[0];
ADIOS_SELECTION* fSel = adios_selection_boundingbox(1, &start , &end);
adios_schedule_read(fp, NULL, "VARIABLENAME", 0, 1, ptr);
ADIOS_CMD(adios_perform_reads(fp, 1));
```
> transform: fix adios_schedule_read

- src/transforms/adios_transform_zlib_write.c
Fix that variables with zero size can not be written if zlib transform is used.
> zlib transform: fix zero byte writes

- src/transforms/adios_transform_blosc_write.c
fix wrong comments for variables used within the transform layer blosc
> transform blosc: fix wrong variable documentation

- config/ac_flexpath.m4
If first search for evpath library fails (searching for .la file), search again for simple .a.   This accommodates the removal of libtool backwards compatibility in evpath.
> Change adios1 to accommodate changes in evpath dev.

- CMakeLists.txt
- src/core/adiosf.c
- src/mxml/mxml-2.9/mxml-string.c
- src/mxml/mxml-2.9/mxml.h
The ADIOS master fails to compile on Apple Clang systems.
```
$ mpicc --version
Apple LLVM version 9.0.0 (clang-900.0.38)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```
> Fix clang build

- src/core/adios_internals_mxml.c
Fix a runtime error in the following situation:
when a user compiles a serial program against the parallel ADIOS libs, there are two ways to use ADIOS without the need to start the app with `mpiexec`:
a) use the moc library instead
b) pass `MPI_COMM_NULL` as communicator
I need the last case in my application but still `adios_open` calls a single `MPI_Comm_rank` which aborts the application.
This check (as it is done in many other places) fixes it.
> serial adios_open with parallel lib

- wrappers/numpy/Makefile
`-lrt` is not available on OSX (Darwin).
Actually it only needs to be added to pre-2013 glibc libs...
Anyway, just append it on Linux now.
Can be merged now.
> Numpy Wrapper: OSX

- doc/manual/adios_noxml_write_api.tex
- src/core/adios.c
- src/core/bp_utils.c
- src/public/adios.h
- tests/C/flexpath_tests/global_range_select/reader.c
- tests/C/flexpath_tests/global_range_select/writer.c
- tests/suite/programs/steps_write.c
- tests/suite/programs/zerolength.c
- tests/test_src/read_points_3d.c
A number of public API function signatures use `char*` for C strings that aren't modified. This change allows `std::string.c_str()` and string literals to be used in C++ without a const cast for every downstream API call.
I also cleaned up a few unused variable warnings.
> Fix const correctness and warnings

- src/core/mpidummy.c
Fix maximum buffer size and warning
```
"could not gather data" directive output truncated writing
22 bytes into a region of size 5 [-Wformat-truncation]
```
See https://github.com/ornladios/ADIOS2/pull/1447
> mpidummy: proper size in snprintf

- src/transforms/adios_transform_zfp_common.h
In ZFP 0.5.1 (latest: 0.5.5), the public API changed slightly. In order to ease maintainance for ADIOS2, let's make ADIOS1 support these newer ZFP releases as well.
Fix #203
Note: this drops support for ZFP 0.5.0 or older.
> ZFP: Support API 0.5.1+

- wrappers/numpy/adios.pyx
- wrappers/numpy/adios_mpi.pyx
Upgrade the conversion of returned scalar attributes to the recommended usage in numpy.
In Numpy 1.16 and newer, the old usage throws a warning of the form ( https://github.com/numpy/numpy/pull/12123 )
```
DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead
```
It is likely this will be removed in Numpy 1.18 and newer, so let us fix this right away.
[`ndarray.item()`](https://numpy.org/devdocs/reference/generated/numpy.ndarray.item.html) is available since a long time/always, so that is a save change.
> Numpy: Scalar Attributes Warning

- configure.ac
For whatever reason, it only causes trouble on some systems, but one is supposed
to use AM_CONDITIONAL for conditionals used in Makefile.am
> fix configure.ac/autotools issue
